<?php
/**
 * Kinvo Configuration File
 * Generated by installer on 2025-07-04 12:57:51
 */

// Database Configuration
define('DB_HOST', 'localhost');
define('DB_NAME', 'simpleinvoice');
define('DB_USER', 'root');
define('DB_PASS', 'root');

// Site Configuration
define('SITE_NAME', 'Kinvo');
define('SITE_URL', 'http://localhost');
define('ADMIN_PASSWORD', 'deprecated'); // Now stored in database

// Debug and Error Configuration
define('APP_DEBUG', false); // Set to false in production

// Error Reporting (set to 0 in production)
if (APP_DEBUG) {
    error_reporting(E_ALL);
    ini_set('display_errors', 1);
} else {
    error_reporting(0);
    ini_set('display_errors', 0);
}

// Timezone
date_default_timezone_set('America/New_York');

// Session Configuration
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}
